steps:
  # Pre-build configuration
  - name: 'us-west2-docker.pkg.dev/github-test-builds-419921/ooctest/ooc-test-custom-image:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - cmake .

  # Build the project
  - name: 'us-west2-docker.pkg.dev/github-test-builds-419921/ooctest/ooc-test-custom-image:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - make

  # Post-build tests
  - name: 'us-west2-docker.pkg.dev/github-test-builds-419921/ooctest/ooc-test-custom-image:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - ctest

# This section is to specify artifacts to be stored
artifacts:
  objects:
    location: 'gs://test-ooc/${_ARTIFACT_NAME}/'
    paths:
      - '/workspace'
    
# Substitutions
substitutions:
  _ARTIFACT_NAME: 'C-Build-Test-$BUILD_ID'
